/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioSplatRouteImport } from './routes/studio.$'

const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSplatRoute = StudioSplatRouteImport.update({
  id: '/studio/$',
  path: '/studio/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/images': typeof ImagesRoute
  '/studio/$': typeof StudioSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/images': typeof ImagesRoute
  '/studio/$': typeof StudioSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/images': typeof ImagesRoute
  '/studio/$': typeof StudioSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/backup' | '/images' | '/studio/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/backup' | '/images' | '/studio/$'
  id: '__root__' | '/' | '/backup' | '/images' | '/studio/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupRoute: typeof BackupRoute
  ImagesRoute: typeof ImagesRoute
  StudioSplatRoute: typeof StudioSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$': {
      id: '/studio/$'
      path: '/studio/$'
      fullPath: '/studio/$'
      preLoaderRoute: typeof StudioSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupRoute: BackupRoute,
  ImagesRoute: ImagesRoute,
  StudioSplatRoute: StudioSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
